/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrgSlugRouteImport } from './routes/org/$slug'
import { Route as OrgSlugSettingsRouteImport } from './routes/org/$slug/settings'
import { Route as OrgSlugPlayersRouteImport } from './routes/org/$slug/players'
import { Route as OrgSlugCourtsRouteImport } from './routes/org/$slug/courts'
import { Route as OrgSlugTournamentsIndexRouteImport } from './routes/org/$slug/tournaments/index'
import { Route as OrgSlugTournamentsTournamentIdRouteImport } from './routes/org/$slug/tournaments/$tournamentId'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugRoute = OrgSlugRouteImport.update({
  id: '/org/$slug',
  path: '/org/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugSettingsRoute = OrgSlugSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => OrgSlugRoute,
} as any)
const OrgSlugPlayersRoute = OrgSlugPlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => OrgSlugRoute,
} as any)
const OrgSlugCourtsRoute = OrgSlugCourtsRouteImport.update({
  id: '/courts',
  path: '/courts',
  getParentRoute: () => OrgSlugRoute,
} as any)
const OrgSlugTournamentsIndexRoute = OrgSlugTournamentsIndexRouteImport.update({
  id: '/tournaments/',
  path: '/tournaments/',
  getParentRoute: () => OrgSlugRoute,
} as any)
const OrgSlugTournamentsTournamentIdRoute =
  OrgSlugTournamentsTournamentIdRouteImport.update({
    id: '/tournaments/$tournamentId',
    path: '/tournaments/$tournamentId',
    getParentRoute: () => OrgSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/org/$slug': typeof OrgSlugRouteWithChildren
  '/org/$slug/courts': typeof OrgSlugCourtsRoute
  '/org/$slug/players': typeof OrgSlugPlayersRoute
  '/org/$slug/settings': typeof OrgSlugSettingsRoute
  '/org/$slug/tournaments/$tournamentId': typeof OrgSlugTournamentsTournamentIdRoute
  '/org/$slug/tournaments/': typeof OrgSlugTournamentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/org/$slug': typeof OrgSlugRouteWithChildren
  '/org/$slug/courts': typeof OrgSlugCourtsRoute
  '/org/$slug/players': typeof OrgSlugPlayersRoute
  '/org/$slug/settings': typeof OrgSlugSettingsRoute
  '/org/$slug/tournaments/$tournamentId': typeof OrgSlugTournamentsTournamentIdRoute
  '/org/$slug/tournaments': typeof OrgSlugTournamentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/org/$slug': typeof OrgSlugRouteWithChildren
  '/org/$slug/courts': typeof OrgSlugCourtsRoute
  '/org/$slug/players': typeof OrgSlugPlayersRoute
  '/org/$slug/settings': typeof OrgSlugSettingsRoute
  '/org/$slug/tournaments/$tournamentId': typeof OrgSlugTournamentsTournamentIdRoute
  '/org/$slug/tournaments/': typeof OrgSlugTournamentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/org/$slug'
    | '/org/$slug/courts'
    | '/org/$slug/players'
    | '/org/$slug/settings'
    | '/org/$slug/tournaments/$tournamentId'
    | '/org/$slug/tournaments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/org/$slug'
    | '/org/$slug/courts'
    | '/org/$slug/players'
    | '/org/$slug/settings'
    | '/org/$slug/tournaments/$tournamentId'
    | '/org/$slug/tournaments'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/org/$slug'
    | '/org/$slug/courts'
    | '/org/$slug/players'
    | '/org/$slug/settings'
    | '/org/$slug/tournaments/$tournamentId'
    | '/org/$slug/tournaments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  OrgSlugRoute: typeof OrgSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/$slug': {
      id: '/org/$slug'
      path: '/org/$slug'
      fullPath: '/org/$slug'
      preLoaderRoute: typeof OrgSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/$slug/settings': {
      id: '/org/$slug/settings'
      path: '/settings'
      fullPath: '/org/$slug/settings'
      preLoaderRoute: typeof OrgSlugSettingsRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/org/$slug/players': {
      id: '/org/$slug/players'
      path: '/players'
      fullPath: '/org/$slug/players'
      preLoaderRoute: typeof OrgSlugPlayersRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/org/$slug/courts': {
      id: '/org/$slug/courts'
      path: '/courts'
      fullPath: '/org/$slug/courts'
      preLoaderRoute: typeof OrgSlugCourtsRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/org/$slug/tournaments/': {
      id: '/org/$slug/tournaments/'
      path: '/tournaments'
      fullPath: '/org/$slug/tournaments/'
      preLoaderRoute: typeof OrgSlugTournamentsIndexRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/org/$slug/tournaments/$tournamentId': {
      id: '/org/$slug/tournaments/$tournamentId'
      path: '/tournaments/$tournamentId'
      fullPath: '/org/$slug/tournaments/$tournamentId'
      preLoaderRoute: typeof OrgSlugTournamentsTournamentIdRouteImport
      parentRoute: typeof OrgSlugRoute
    }
  }
}

interface OrgSlugRouteChildren {
  OrgSlugCourtsRoute: typeof OrgSlugCourtsRoute
  OrgSlugPlayersRoute: typeof OrgSlugPlayersRoute
  OrgSlugSettingsRoute: typeof OrgSlugSettingsRoute
  OrgSlugTournamentsTournamentIdRoute: typeof OrgSlugTournamentsTournamentIdRoute
  OrgSlugTournamentsIndexRoute: typeof OrgSlugTournamentsIndexRoute
}

const OrgSlugRouteChildren: OrgSlugRouteChildren = {
  OrgSlugCourtsRoute: OrgSlugCourtsRoute,
  OrgSlugPlayersRoute: OrgSlugPlayersRoute,
  OrgSlugSettingsRoute: OrgSlugSettingsRoute,
  OrgSlugTournamentsTournamentIdRoute: OrgSlugTournamentsTournamentIdRoute,
  OrgSlugTournamentsIndexRoute: OrgSlugTournamentsIndexRoute,
}

const OrgSlugRouteWithChildren =
  OrgSlugRoute._addFileChildren(OrgSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  OrgSlugRoute: OrgSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
